In [1]:
!pip3 install numpy

In [2]:
my_list=[1,2,3]

In [6]:
import numpy as np

# convert list to an array

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,2)     #(start,stop,step)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.66959867, 0.99463895, 0.77960662, 0.14696983, 0.26323381])

In [24]:
np.random.rand(5,5)

array([[0.58238075, 0.4420735 , 0.39658116, 0.30723734, 0.36899849],
       [0.75394928, 0.06664271, 0.20057521, 0.58645772, 0.8684759 ],
       [0.84379931, 0.15108209, 0.6221725 , 0.38416137, 0.55237238],
       [0.22819079, 0.71414163, 0.1696054 , 0.15260814, 0.95633407],
       [0.88230577, 0.96678141, 0.13288269, 0.77672268, 0.94193422]])

In [25]:
np.random.randn(2)

array([-0.93444926,  1.39454571])

In [26]:
np.random.randn(4,4)

array([[ 0.80097607,  3.11461113,  0.81517962, -2.76648108],
       [ 0.17875941, -1.33463459,  1.2440708 , -1.46914022],
       [-1.03918029,  0.77560656, -1.56485202,  0.05304757],
       [-0.0734278 , -0.28464568,  0.23090022, -1.15721529]])

In [28]:
np.random.randint(1,100)    #random int btw 1 to 100

29

In [29]:
np.random.randint(1,100,10) 

array([ 4, 82, 93, 59, 98, 64, 76, 23, 63, 53])

In [31]:
arr=np.arange(25)

In [32]:
ranarr=np.random.randint(0,5,10)

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr.max()

4

In [36]:
ranarr.min()

0

In [38]:
ranarr.argmax()      #index location

9

In [39]:
arr.shape

(25,)

In [40]:
arr.dtype

dtype('int64')

In [41]:
from numpy.random import randint   # can directly use now

In [42]:
randint(5)

4

# class2

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#slicing

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [52]:
arr[0:5]=100      #broadcast value

In [51]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [53]:
arr=np.arange(10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
slice_data=arr[0:5]

In [66]:
slice_data

array([0, 1, 2, 3, 4])

In [68]:
slice_data[:]=100

In [69]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

#this shows that the values are not just copies it;s just a viwew to the original array.

##if we specially want to indicate copy 

In [70]:
arr_copy=arr.copy()

In [71]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [72]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [73]:
arr_copy[:]=100

In [74]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

2D array

In [75]:
arr_2d=np.array([[5,10,15],[20,25,30],[30,40,45]])

In [76]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [77]:
arr_2d[0][0]    #first row nad first column

5

OR

In [79]:
arr_2d[0,0]    #row,col

5

In [81]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [82]:
arr=np.arange(1,11)

In [83]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
bool_arr=arr > 5

In [86]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [88]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [89]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])